# Generated by Django 5.1.6 on 2025-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aihandler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
